name: Build blueberry-k3s image

on:
  workflow_call:

jobs:
  build-k3s:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile.k3s
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          oci: false

      - uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: latest

